
[urgency_low]
    background = "#6592A380"
    foreground = "#CCF1FFE6"
    frame_color = "#6592A303"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#3A5E6B80"
    foreground = "#CCF2FFE6"
    frame_color = "#3A5E6B03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
